# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    
    - name: Alibaba Cloud Container Registry (ACR) Login
      uses: aliyun/acr-login@v1
      with:
        username: "${{secrets.ALI_ACR_USERNAME}}"
        password: "${{secrets.ALI_ACR_PASSWD}}"
        region-id: "cn-hongkong"
        login-server: "registry.cn-hongkong.aliyuncs.com"

    - name: Build and Push Docker Image
      run: |
        docker build --tag registry.cn-hongkong.aliyuncs.com/webnotes/frontend:latest .
        docker push registry.cn-hongkong.aliyuncs.com/webnotes/frontend:latest
